#!/bin/bash

# Generate package files using online netinstall.yaml directly
# using eos-packageslist
eos-packagelist "Desktop-Base + Common packages" > eos-base-group
eos-packagelist "XFCE4-Desktop" > xfce4    
eos-packagelist "i3-Window-Manager" > i3
eos-packagelist "KDE-Desktop" > kde      
eos-packagelist "GNOME-Desktop" > gnome
eos-packagelist "MATE-Desktop" > mate
eos-packagelist "Cinnamon-Desktop" > cinnamon
eos-packagelist "Budgie-Desktop" > budgie
eos-packagelist "LXQT-Desktop" > lxqt
eos-packagelist "LXDE-Desktop" > lxde
eos-packagelist "BSPWM Edition" > bspwm
eos-packagelist "Openbox Edition" > openbox
eos-packagelist "Qtile Edition" > qtile
eos-packagelist "Sway Edition" > sway
eos-packagelist "Worm Edition" > worm
